<ul class="collapse-content">
	<li><a id="streams_0901" class="play_link">以賽亞書54章11節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0902" class="play_link">腓立比書1章29節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0903" class="play_link">馬可福音6章48節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0904" class="play_link">約書亞記6章5節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0905" class="play_link">以賽亞書30章18節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0906" class="play_link">希伯來書1章11節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0907" class="play_link">詩篇46篇1節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0908" class="play_link">詩篇4篇1節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0909" class="play_link">馬太福音13章5節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0910" class="play_link">詩篇138篇8節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0911" class="play_link">希伯來書6章15節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0912" class="play_link">雅歌8章5節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0913" class="play_link">出埃及記34章2節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0914" class="play_link">馬可福音8章34節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0915" class="play_link">雅歌4章16節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0916" class="play_link">列王記上17章3節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0917" class="play_link">撒母耳記上3章18節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0918" class="play_link">箴言29章18節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0919" class="play_link">約翰福音15章1節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0920" class="play_link">約翰福音11章40節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0921" class="play_link">腓立比書3章8節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0922" class="play_link">路加福音22章31-32節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0923" class="play_link">約翰福音7章38節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0924" class="play_link">使徒行傳16章7節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0925" class="play_link">詩篇42篇9節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0926" class="play_link">哥林多後書5章7節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0927" class="play_link">約伯記33章24節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0928" class="play_link">約翰福音16章33節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0929" class="play_link">詩篇109篇4節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
	<li><a id="streams_0930" class="play_link">申命記32章11-12節<span class="icon"><i class="far fa-play-circle"></i></span></a></li>
</ul>